[package]

name = "stainless"
version = "0.1.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Organized, flexible testing framework."
repository = "https://github.com/reem/stainless"
license = "MIT"

[lib]

name = "stainless"
path = "src/lib.rs"
plugin = true

